import { Lesson } from '../../shared/lesson';

export const LESSONS: Lesson[] = [
  {
    id: 1,
    description:
      'Angular Tutorial For Beginners - Build Your First App - Hello World Step By Step',
    duration: '4:17',
    seqNo: 1,
    courseId: 5,
  },
  {
    id: 2,
    description: 'Building Your First  Component - Component Composition',
    duration: '2:07',
    seqNo: 2,
    courseId: 5,
  },
  {
    id: 3,
    description: 'Component @Input - How To Pass Input Data To an  Component',
    duration: '2:33',
    seqNo: 3,
    courseId: 5,
  },
  {
    id: 4,
    description: ' Component Events - Using @Output to create custom events',
    duration: '4:44',
    seqNo: 4,
    courseId: 5,
  },
  {
    id: 5,
    description: ' Component Templates - Inline Vs External',
    duration: '2:55',
    seqNo: 5,
    courseId: 5,
  },
  {
    id: 6,
    description: 'Styling  Components - Learn About Component Style Isolation',
    duration: '3:27',
    seqNo: 6,
    courseId: 5,
  },
  {
    id: 7,
    description: ' Component Interaction - Extended Components Example',
    duration: '9:22',
    seqNo: 7,
    courseId: 5,
  },
  {
    id: 8,
    description: ' Components Tutorial For Beginners - Components Exercise !',
    duration: '1:26',
    seqNo: 8,
    courseId: 5,
  },
  {
    id: 9,
    description:
      ' Components Tutorial For Beginners - Components Exercise Solution Inside',
    duration: '2:08',
    seqNo: 9,
    courseId: 5,
  },
  {
    id: 10,
    description:
      ' Directives - Inputs, Output Event Emitters and How To Export Template References',
    duration: '4:01',
    seqNo: 10,
    courseId: 5,
  },
  {
    id: 11,
    description: 'Course Helicopter View',
    duration: '08:19',
    seqNo: 1,
    courseId: 6,
  },
  {
    id: 12,
    description: 'Installing Git, Node, NPM and Choosing an IDE',
    duration: '04:17',
    seqNo: 2,
    courseId: 6,
  },
  {
    id: 13,
    description:
      'Installing The Lessons Code - Learn Why Its Essential To Use NPM 5',
    duration: '06:05',
    seqNo: 3,
    courseId: 6,
  },
  {
    id: 14,
    description: 'How To Run Node In TypeScript With Hot Reloading',
    duration: '03:57',
    seqNo: 4,
    courseId: 6,
  },
  {
    id: 15,
    description: 'Guided Tour Of The Sample Application',
    duration: '06:00',
    seqNo: 5,
    courseId: 6,
  },
  {
    id: 16,
    description: 'Client Side Authentication Service - API Design',
    duration: '04:53',
    seqNo: 6,
    courseId: 6,
  },
  {
    id: 17,
    description: 'Client Authentication Service - Design and Implementation',
    duration: '09:14',
    seqNo: 7,
    courseId: 6,
  },
  {
    id: 18,
    description:
      'The New Angular HTTP Client - Doing a POST Call To The Server',
    duration: '06:08',
    seqNo: 8,
    courseId: 6,
  },
  {
    id: 19,
    description: 'User Sign Up Server-Side Implementation in Express',
    duration: '08:50',
    seqNo: 9,
    courseId: 6,
  },
  {
    id: 20,
    description: 'Introduction To Cryptographic Hashes - A Running Demo',
    duration: '05:46',
    seqNo: 10,
    courseId: 6,
  },
  {
    id: 21,
    description:
      'Some Interesting Properties Of Hashing Functions - Validating Passwords',
    duration: '06:31',
    seqNo: 11,
    courseId: 6,
  },
  {
    id: 22,
    description:
      'Course Kick-Off - Install Node, NPM, IDE And Service Workers Section Code',
    duration: '07:19',
    seqNo: 1,
    courseId: 7,
  },
  {
    id: 23,
    description: 'Service Workers In a Nutshell - Service Worker Registration',
    duration: '6:59',
    seqNo: 2,
    courseId: 7,
  },
  {
    id: 24,
    description:
      'Service Workers Hello World - Lifecycle Part 1 and PWA Chrome Dev Tools',
    duration: '7:28',
    seqNo: 3,
    courseId: 7,
  },
  {
    id: 25,
    description:
      'Service Workers and Application Versioning - Install & Activate Lifecycle Phases',
    duration: '10:17',
    seqNo: 4,
    courseId: 7,
  },
  {
    id: 26,
    description:
      'Downloading The Offline Page - The Service Worker Installation Phase',
    duration: '09:50',
    seqNo: 5,
    courseId: 7,
  },
  {
    id: 27,
    description: 'Introduction to the Cache Storage PWA API',
    duration: '04:44',
    seqNo: 6,
    courseId: 7,
  },
  {
    id: 28,
    description: 'View Service Workers HTTP Interception Features In Action',
    duration: '06:07',
    seqNo: 7,
    courseId: 7,
  },
  {
    id: 29,
    description: 'Service Workers Error Handling - Serving The Offline Page',
    duration: '5:38',
    seqNo: 8,
    courseId: 7,
  },
  {
    id: 30,
    description: 'Development Environment Setup',
    duration: '5:38',
    seqNo: 1,
    courseId: 1,
  },

  {
    id: 31,
    description: 'Introduction to the Firebase Ecosystem',
    duration: '5:12',
    seqNo: 2,
    courseId: 1,
  },
  {
    id: 32,
    description: 'Importing Data into Firestore',
    duration: '4:07',
    seqNo: 3,
    courseId: 1,
  },
  {
    id: 33,
    description: 'Firestore Documents in Detail',
    duration: '7:32',
    seqNo: 4,
    courseId: 1,
  },
  {
    id: 34,
    description: 'Firestore Collections in Detail',
    duration: '6:28',
    seqNo: 5,
    courseId: 1,
  },
  {
    id: 35,
    description: 'Firestore Unique Identifiers',
    duration: '4:38',
    seqNo: 6,
    courseId: 1,
  },
  {
    id: 36,
    description: 'Querying Firestore Collections',
    duration: '7:54',
    seqNo: 7,
    courseId: 1,
  },
  {
    id: 37,
    description: 'Firebase Security Rules In Detail',
    duration: '5:31',
    seqNo: 8,
    courseId: 1,
  },
  {
    id: 38,
    description: 'Firebase Cloud Functions In Detail',
    duration: '8:19',
    seqNo: 9,
    courseId: 1,
  },
  {
    id: 39,
    description: 'Firebase Storage In Detail',
    duration: '7:05',
    seqNo: 10,
    courseId: 1,
  },
  {
    id: 40,
    description: 'Angular Testing Course - Helicopter View',
    duration: '5:38',
    seqNo: 1,
    courseId: 12,
  },
  {
    id: 41,
    description: 'Setting Up the Development Environment',
    duration: '5:12',
    seqNo: 2,
    courseId: 12,
  },
  {
    id: 42,
    description: 'Introduction to Jasmine, Spies and specs',
    duration: '4:07',
    seqNo: 3,
    courseId: 12,
  },
  {
    id: 43,
    description: 'Introduction to Service Testing',
    duration: '7:32',
    seqNo: 4,
    courseId: 12,
  },
  {
    id: 44,
    description: 'Settting up the Angular TestBed',
    duration: '6:28',
    seqNo: 5,
    courseId: 12,
  },
  {
    id: 45,
    description: 'Mocking Angular HTTP requests',
    duration: '4:38',
    seqNo: 6,
    courseId: 12,
  },
  {
    id: 46,
    description: 'Simulating Failing HTTP Requests',
    duration: '7:54',
    seqNo: 7,
    courseId: 12,
  },
  {
    id: 47,
    description: 'Introduction to Angular Component Testing',
    duration: '5:31',
    seqNo: 8,
    courseId: 12,
  },
  {
    id: 48,
    description: 'Testing Angular Components without the DOM',
    duration: '8:19',
    seqNo: 9,
    courseId: 12,
  },
  {
    id: 49,
    description: 'Testing Angular Components with the DOM',
    duration: '7:05',
    seqNo: 10,
    courseId: 12,
  },
  {
    id: 50,
    description: 'Welcome to the Angular Ngrx Course',
    duration: '6:53',
    seqNo: 1,
    courseId: 4,
  },
  {
    id: 51,
    description: 'The Angular Ngrx Architecture Course - Helicopter View',
    duration: '5:52',
    seqNo: 2,
    courseId: 4,
  },
  {
    id: 52,
    description:
      'The Origins of Flux - Understanding the Famous Facebook Bug Problem',
    duration: '8:17',
    seqNo: 3,
    courseId: 4,
  },
  {
    id: 53,
    description: "Custom Global Events - Why Don't They Scale In Complexity?",
    duration: '7:47',
    seqNo: 4,
    courseId: 4,
  },
  {
    id: 54,
    description:
      'The Flux Architecture - How Does it Solve Facebook Counter Problem?',
    duration: '9:22',
    seqNo: 5,
    courseId: 4,
  },
  {
    id: 55,
    description: 'Unidirectional Data Flow And The Angular Development Mode',
    duration: '7:07',
    seqNo: 6,
    courseId: 4,
  },
  {
    id: 56,
    description: 'Dispatching an Action - Implementing the Login Component',
    duration: '4:39',
    seqNo: 7,
    courseId: 4,
  },
  {
    id: 57,
    description: 'Setting Up the Ngrx DevTools - Demo',
    duration: '4:44',
    seqNo: 8,
    courseId: 4,
  },
  {
    id: 58,
    description: 'Understanding Reducers - Writing Our First Reducer',
    duration: '9:10',
    seqNo: 9,
    courseId: 4,
  },
  {
    id: 59,
    description: 'How To Define the Store Initial State',
    duration: '9:10',
    seqNo: 10,
    courseId: 4,
  },

  {
    id: 60,
    description: 'Introduction to NestJs',
    duration: '4:29',
    seqNo: 1,
    courseId: 14,
  },
  {
    id: 61,
    description: 'Development Environment Setup',
    duration: '6:37',
    seqNo: 2,
    courseId: 14,
  },
  {
    id: 62,
    description: 'Setting up a MongoDB Database',
    duration: '6:38',
    seqNo: 3,
    courseId: 14,
  },
  {
    id: 63,
    description: 'CRUD with NestJs - Controllers and Repositories',
    duration: '12:12',
    seqNo: 4,
    courseId: 14,
  },
  {
    id: 64,
    description: 'First REST endpoint - Get All Courses',
    duration: '3:42',
    seqNo: 5,
    courseId: 14,
  },
  {
    id: 65,
    description: 'Error Handling',
    duration: '5:15',
    seqNo: 6,
    courseId: 14,
  },
  {
    id: 66,
    description: 'NestJs Middleware',
    duration: '7:08',
    seqNo: 7,
    courseId: 14,
  },
  {
    id: 67,
    description: 'Authentication in NestJs',
    duration: '13:22',
    seqNo: 8,
    courseId: 14,
  },
  {
    id: 68,
    description: 'Authorization in NestJs',
    duration: '6:43',
    seqNo: 9,
    courseId: 14,
  },
  {
    id: 69,
    description: 'Guards & Interceptors',
    duration: '8:16',
    seqNo: 10,
    courseId: 14,
  },
];
